stages:
  - check


uv:
  stage: check
  variables:
    PYTHON_VERSION: "3.11"
    UV_LINK_MODE: copy
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  image: ghcr.io/astral-sh/uv:python$PYTHON_VERSION-alpine
  script:
    - uv sync --only-group lint --only-group test
    - uv cache prune --ci

lint:
  stage: check
  image: ghcr.io/astral-sh/uv:latest
  script:
    - ruff check .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

type-check:
  stage: check
  image: ghcr.io/astral-sh/uv:latest
  script:
    - mypy .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

tests:
  stage: check
  image: ghcr.io/astral-sh/uv:latest
  script:
    - pytest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
