stages:
  - lint
  - test

ruff:
  stage: lint
  image: python:3.11
  before_script:
    - pip install ruff
  script:
    - ruff check .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

mypy:
  stage: lint
  image: python:3.11
  before_script:
    - pip install mypy
  script:
    - mypy .
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

pytest:
  stage: test
  image: python:3.11
  before_script:
    - pip install pytest
  script:
    - pytest --maxfail=1 --disable-warnings -q
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
