services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: bash -c "alembic upgrade head && python3 -m uvicorn src.redkeds.main.main:get_app --host=0.0.0.0 --port=8000"
    env_file:
      - ".env"
    depends_on:
      - database
    volumes:
      - ./media:/media

  database:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_LOGIN}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
