[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aliaksei Yafremau", email = "aleksey.yafremau@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
app = "app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
lint = [
    "mypy>=1.16.0",
    "ruff>=0.11.13",
]

[tool.mypy]
exclude = [
	# Игнорировать папку "tests" и все её подпапки
	"^tests/",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D104", # Не нужно писать docstring для модулей
    "D213", # Не нужно начинать docstring с второй строки
    "D203", # Не нужно писать docstring с первой строки
    "S101", # Возможность использования assert
    "EM101", # Возможность использования строки при вызове ошибки
]