from typing import Protocol

from redkeds.domain.entities.user import User
from redkeds.domain.entities.user_id import UserId


class UserGateway(Protocol):
    async def save_user(self, user: User) -> None: ...

    async def get_user_by_id(self, user_id: UserId) -> User: ...

    async def get_user_by_email(self, email: str) -> User: ...

    async def update_user(self, user: User) -> None: ...

    async def delete_user(self, user_id: UserId) -> None: ...
