from typing import Protocol

from redkeds.domain.entities.showcase import ShowcaseId, Work, WorkId


class WorkGateway(Protocol):
    async def get_work_by_id(self, work_id: WorkId) -> Work: ...

    async def get_showcase_works_by_id(self, showcase_id: ShowcaseId) -> list[Work]: ...

    async def save_work(self, work: Work) -> WorkId: ...

    async def update_work(self, work: Work) -> None: ...

    async def delete_work(self, work_id: WorkId) -> None: ...
