"""Add default photos

Revision ID: 5828d843eecd
Revises: 84716f24e2ad
Create Date: 2025-08-19 21:32:10.019576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5828d843eecd'
down_revision: Union[str, Sequence[str], None] = '84716f24e2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('default_photo', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'default_photos', ['default_photo'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_photo')
    op.drop_table('default_photos')
    # ### end Alembic commands ###
