"""Добавил email и nickname

Revision ID: ab1c6729bb76
Revises: dd2db88331cf
Create Date: 2025-08-01 22:13:52.242033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1c6729bb76'
down_revision: Union[str, Sequence[str], None] = 'dd2db88331cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user1_id', sa.Uuid(), nullable=False),
    sa.Column('user2_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.alter_column('users', 'photo',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.alter_column('works', 'file_path',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'file_path',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'photo',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'email')
    op.drop_table('chat_messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
