"""initial

Revision ID: c7b6c878e44d
Revises: 
Create Date: 2025-08-12 14:20:07.487750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b6c878e44d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skips')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skips',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('showcase_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['showcase_id'], ['showcases.id'], name=op.f('skips_showcase_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('skips_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('skips_pkey'))
    )
    # ### end Alembic commands ###
