"""add 'likes' table

Revision ID: dd2db88331cf
Revises: f3f6cf951daa
Create Date: 2025-08-01 15:50:40.365248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2db88331cf'
down_revision: Union[str, Sequence[str], None] = 'f3f6cf951daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('showcase_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['showcase_id'], ['showcases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'showcase_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
