"""Add type name display

Revision ID: df737bc5de97
Revises: 316b774465e2
Create Date: 2025-08-13 12:07:24.412652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df737bc5de97'
down_revision: Union[str, Sequence[str], None] = '316b774465e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


type_name_display = sa.Enum("USERNAME", "NICKNAME", name="namedisplay")

def upgrade() -> None:
    """Upgrade schema."""
    type_name_display.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_display', sa.Enum('USERNAME', 'NICKNAME', name='namedisplay'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name_display')
    type_name_display.drop(op.get_bind())
    # ### end Alembic commands ###