"""add cascade delete in showcase

Revision ID: ee90f13273f5
Revises: 5828d843eecd
Create Date: 2025-08-26 01:19:31.342085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee90f13273f5'
down_revision: Union[str, Sequence[str], None] = '5828d843eecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('showcase_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['showcase_id'], ['showcases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('channels')
    op.add_column('showcases', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, 'showcases', ['user_id'])
    op.create_foreign_key(None, 'showcases', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('default_photo', sa.Uuid(), nullable=True))
    op.add_column('users', sa.Column('name_display', sa.Enum('USERNAME', 'NICKNAME', name='namedisplay'), nullable=True))
    op.create_unique_constraint(None, 'users', ['nickname'])
    op.drop_constraint(op.f('users_showcase_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'default_photos', ['default_photo'], ['id'])
    op.drop_column('users', 'showcase_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('showcase_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_showcase_id_fkey'), 'users', 'showcases', ['showcase_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'name_display')
    op.drop_column('users', 'default_photo')
    op.drop_constraint(None, 'showcases', type_='foreignkey')
    op.drop_constraint(None, 'showcases', type_='unique')
    op.drop_column('showcases', 'user_id')
    op.create_table('channels',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('channels_pkey'))
    )
    op.drop_table('skips')
    op.drop_table('default_photos')
    # ### end Alembic commands ###
