from typing import Protocol

from redkeds.domain.entities.file_id import FileId


class FileManager(Protocol):
    async def save(self, file: bytes) -> FileId: ...

    async def read(self, file_id: FileId) -> bytes: ...

    async def update(self, file_id: FileId, file: bytes) -> None: ...

    async def delete(self, file_id: FileId) -> None: ...
